#!/usr/bin/env python3
"""Builds a combined landing page over DocC's static-hosting archives.

DocC's --transform-for-static-hosting output is one self-contained archive
per target — Sources/<repo>/<Target> in via `generate-documentation`, ending
up here as <site_root>/<repo>/<Target>/. Nothing in DocC assembles multiple
targets into one navigable site (see PLAN §8a); this script is that missing
piece; it never modifies the archives.

The entry point inside each archive is always
`documentation/<lowercased-target-name>/index.html` — confirmed by
generating one and inspecting it directly rather than assumed, since it is
undocumented as a stable contract.

Usage: generate-docs-index.py <site_root> <output_html_path>
"""
import sys
from pathlib import Path


def discover(site_root: Path) -> dict[str, list[str]]:
    repos: dict[str, list[str]] = {}
    for repo_dir in sorted(site_root.iterdir()):
        if not repo_dir.is_dir():
            continue
        targets = []
        for target_dir in sorted(repo_dir.iterdir()):
            entry = target_dir / "documentation" / target_dir.name.lower() / "index.html"
            if entry.exists():
                targets.append(target_dir.name)
        if targets:
            repos[repo_dir.name] = targets
    return repos


def render(repos: dict[str, list[str]]) -> str:
    sections = []
    for repo, targets in repos.items():
        items = "\n".join(
            f'      <li><a href="./{repo}/{t}/documentation/{t.lower()}/">{t}</a></li>'
            for t in targets
        )
        sections.append(f"    <section>\n      <h2>{repo}</h2>\n      <ul>\n{items}\n      </ul>\n    </section>")
    body = "\n".join(sections)
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Flight reference documentation</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 720px; margin: 60px auto; padding: 0 20px; color: #16161d; }}
  h1 {{ margin-bottom: 4px; }}
  .sub {{ color: #6b6b78; margin-top: 0; }}
  section {{ margin-top: 32px; }}
  h2 {{ font-size: 1rem; text-transform: uppercase; letter-spacing: 0.05em; color: #6b6b78; border-bottom: 1px solid #e5e5ec; padding-bottom: 6px; }}
  ul {{ list-style: none; padding: 0; }}
  li {{ padding: 6px 0; }}
  a {{ color: #2f6df6; text-decoration: none; font-weight: 600; }}
  a:hover {{ text-decoration: underline; }}
</style>
</head>
<body>
  <h1>Flight reference documentation</h1>
  <p class="sub">Generated by flight-school/.github/workflows/docs.yml — see the
     <a href="https://github.com/Swift-Flight/flight-school">flight-school</a> repository
     for the tutorial and narrative guides (no fixed production domain yet).</p>
{body}
</body>
</html>
"""


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    site_root, output_path = Path(sys.argv[1]), Path(sys.argv[2])
    repos = discover(site_root)
    if not repos:
        print(f"no DocC archives found under {site_root}", file=sys.stderr)
        sys.exit(1)
    output_path.write_text(render(repos))
    total = sum(len(v) for v in repos.values())
    print(f"wrote {output_path}: {len(repos)} repos, {total} targets")


if __name__ == "__main__":
    main()
